namespace NK_COLLECTION.Presentacion.Productos
{
    partial class Frm_catalogo_rapido
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            DataGridViewCellStyle headerStyle = new DataGridViewCellStyle();
            DataGridViewCellStyle rowStyle = new DataGridViewCellStyle();
            pnlEncabezado = new Guna.UI2.WinForms.Guna2Panel();
            btnVolver = new Guna.UI2.WinForms.Guna2Button();
            lblSubtitulo = new Label();
            lblTitulo = new Label();
            pnlListado = new Guna.UI2.WinForms.Guna2ShadowPanel();
            lblTotal = new Label();
            btnBuscar = new Guna.UI2.WinForms.Guna2Button();
            txtBuscar = new Guna.UI2.WinForms.Guna2TextBox();
            dgvCatalogo = new Guna.UI2.WinForms.Guna2DataGridView();
            colId = new DataGridViewTextBoxColumn();
            colNombre = new DataGridViewTextBoxColumn();
            colDescripcion = new DataGridViewTextBoxColumn();
            colEstado = new DataGridViewTextBoxColumn();
            pnlFormulario = new Guna.UI2.WinForms.Guna2ShadowPanel();
            lblSeleccion = new Label();
            btnNuevo = new Guna.UI2.WinForms.Guna2Button();
            btnBorrar = new Guna.UI2.WinForms.Guna2Button();
            btnEditar = new Guna.UI2.WinForms.Guna2Button();
            btnGuardar = new Guna.UI2.WinForms.Guna2Button();
            txtDescripcion = new Guna.UI2.WinForms.Guna2TextBox();
            lblDescripcion = new Label();
            txtNombre = new Guna.UI2.WinForms.Guna2TextBox();
            lblNombre = new Label();
            lblFormulario = new Label();
            pnlEncabezado.SuspendLayout();
            pnlListado.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)dgvCatalogo).BeginInit();
            pnlFormulario.SuspendLayout();
            SuspendLayout();
            // header
            pnlEncabezado.BackColor = Color.FromArgb(248, 241, 242);
            pnlEncabezado.Controls.Add(btnVolver);
            pnlEncabezado.Controls.Add(lblSubtitulo);
            pnlEncabezado.Controls.Add(lblTitulo);
            pnlEncabezado.Dock = DockStyle.Top;
            pnlEncabezado.Location = new Point(0, 0);
            pnlEncabezado.Name = "pnlEncabezado";
            pnlEncabezado.Size = new Size(1556, 120);
            btnVolver.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            btnVolver.BorderColor = Color.FromArgb(190, 160, 165);
            btnVolver.BorderRadius = 8;
            btnVolver.BorderThickness = 1;
            btnVolver.FillColor = Color.White;
            btnVolver.Font = new Font("Book Antiqua", 9F, FontStyle.Bold);
            btnVolver.ForeColor = Color.FromArgb(64, 0, 0);
            btnVolver.Location = new Point(1325, 39);
            btnVolver.Name = "btnVolver";
            btnVolver.Size = new Size(195, 45);
            btnVolver.Text = "Volver a productos";
            btnVolver.Click += btnVolver_Click;
            lblSubtitulo.AutoSize = true;
            lblSubtitulo.Font = new Font("Book Antiqua", 9.5F);
            lblSubtitulo.ForeColor = Color.FromArgb(100, 83, 86);
            lblSubtitulo.Location = new Point(38, 72);
            lblSubtitulo.Name = "lblSubtitulo";
            lblSubtitulo.Size = new Size(476, 23);
            lblSubtitulo.Text = "Guarde, edite o desactive registros del catálogo.";
            lblTitulo.AutoSize = true;
            lblTitulo.Font = new Font("Book Antiqua", 20F, FontStyle.Bold);
            lblTitulo.ForeColor = Color.FromArgb(64, 0, 0);
            lblTitulo.Location = new Point(33, 22);
            lblTitulo.Name = "lblTitulo";
            lblTitulo.Size = new Size(303, 47);
            lblTitulo.Text = "Gestión de catálogo";
            // listado
            pnlListado.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left;
            pnlListado.BackColor = Color.Transparent;
            pnlListado.Controls.Add(lblTotal);
            pnlListado.Controls.Add(btnBuscar);
            pnlListado.Controls.Add(txtBuscar);
            pnlListado.Controls.Add(dgvCatalogo);
            pnlListado.FillColor = Color.White;
            pnlListado.Location = new Point(28, 128);
            pnlListado.Name = "pnlListado";
            pnlListado.Radius = 12;
            pnlListado.ShadowColor = Color.FromArgb(90, 64, 0, 0);
            pnlListado.ShadowDepth = 18;
            pnlListado.ShadowShift = 2;
            pnlListado.Size = new Size(950, 706);
            lblTotal.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            lblTotal.AutoSize = true;
            lblTotal.Font = new Font("Book Antiqua", 8.5F, FontStyle.Bold);
            lblTotal.ForeColor = Color.FromArgb(98, 48, 56);
            lblTotal.Location = new Point(31, 664);
            lblTotal.Name = "lblTotal";
            lblTotal.Size = new Size(94, 20);
            lblTotal.Text = "Registros: 0";
            btnBuscar.BorderRadius = 8;
            btnBuscar.FillColor = Color.FromArgb(64, 0, 0);
            btnBuscar.Font = new Font("Book Antiqua", 8.5F, FontStyle.Bold);
            btnBuscar.ForeColor = Color.White;
            btnBuscar.Location = new Point(770, 25);
            btnBuscar.Name = "btnBuscar";
            btnBuscar.Size = new Size(145, 42);
            btnBuscar.Text = "Buscar";
            btnBuscar.Click += btnBuscar_Click;
            txtBuscar.BorderColor = Color.FromArgb(216, 216, 216);
            txtBuscar.BorderRadius = 8;
            txtBuscar.DefaultText = "";
            txtBuscar.FillColor = Color.FromArgb(248, 241, 242);
            txtBuscar.Font = new Font("Segoe UI", 9F);
            txtBuscar.Location = new Point(31, 25);
            txtBuscar.Margin = new Padding(4, 6, 4, 6);
            txtBuscar.Name = "txtBuscar";
            txtBuscar.PlaceholderText = "Buscar por nombre";
            txtBuscar.SelectedText = "";
            txtBuscar.Size = new Size(720, 42);
            txtBuscar.KeyDown += txtBuscar_KeyDown;
            // grid
            dgvCatalogo.AllowUserToAddRows = false;
            dgvCatalogo.AllowUserToDeleteRows = false;
            dgvCatalogo.AllowUserToResizeRows = false;
            dgvCatalogo.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            dgvCatalogo.BackgroundColor = Color.White;
            dgvCatalogo.BorderStyle = BorderStyle.None;
            headerStyle.Alignment = DataGridViewContentAlignment.MiddleLeft;
            headerStyle.BackColor = Color.FromArgb(64, 0, 0);
            headerStyle.Font = new Font("Book Antiqua", 8.5F, FontStyle.Bold);
            headerStyle.ForeColor = Color.White;
            headerStyle.SelectionBackColor = Color.FromArgb(64, 0, 0);
            headerStyle.SelectionForeColor = Color.White;
            headerStyle.WrapMode = DataGridViewTriState.True;
            dgvCatalogo.ColumnHeadersDefaultCellStyle = headerStyle;
            dgvCatalogo.ColumnHeadersHeight = 44;
            dgvCatalogo.Columns.AddRange(new DataGridViewColumn[] { colId, colNombre, colDescripcion, colEstado });
            rowStyle.Alignment = DataGridViewContentAlignment.MiddleLeft;
            rowStyle.BackColor = Color.White;
            rowStyle.Font = new Font("Segoe UI", 8.7F);
            rowStyle.ForeColor = Color.FromArgb(45, 45, 45);
            rowStyle.SelectionBackColor = Color.FromArgb(241, 225, 228);
            rowStyle.SelectionForeColor = Color.FromArgb(64, 0, 0);
            dgvCatalogo.DefaultCellStyle = rowStyle;
            dgvCatalogo.EnableHeadersVisualStyles = false;
            dgvCatalogo.GridColor = Color.FromArgb(238, 228, 230);
            dgvCatalogo.Location = new Point(31, 84);
            dgvCatalogo.MultiSelect = false;
            dgvCatalogo.Name = "dgvCatalogo";
            dgvCatalogo.ReadOnly = true;
            dgvCatalogo.RowHeadersVisible = false;
            dgvCatalogo.RowTemplate.Height = 40;
            dgvCatalogo.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgvCatalogo.Size = new Size(884, 560);
            dgvCatalogo.SelectionChanged += dgvCatalogo_SelectionChanged;
            colId.HeaderText = "ID"; colId.Name = "colId"; colId.ReadOnly = true; colId.Width = 80;
            colNombre.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill; colNombre.FillWeight = 130F; colNombre.HeaderText = "Nombre"; colNombre.Name = "colNombre"; colNombre.ReadOnly = true;
            colDescripcion.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill; colDescripcion.HeaderText = "Descripción"; colDescripcion.Name = "colDescripcion"; colDescripcion.ReadOnly = true;
            colEstado.HeaderText = "Estado"; colEstado.Name = "colEstado"; colEstado.ReadOnly = true; colEstado.Width = 110;
            // form panel
            pnlFormulario.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            pnlFormulario.BackColor = Color.Transparent;
            pnlFormulario.Controls.Add(lblSeleccion);
            pnlFormulario.Controls.Add(btnNuevo);
            pnlFormulario.Controls.Add(btnBorrar);
            pnlFormulario.Controls.Add(btnEditar);
            pnlFormulario.Controls.Add(btnGuardar);
            pnlFormulario.Controls.Add(txtDescripcion);
            pnlFormulario.Controls.Add(lblDescripcion);
            pnlFormulario.Controls.Add(txtNombre);
            pnlFormulario.Controls.Add(lblNombre);
            pnlFormulario.Controls.Add(lblFormulario);
            pnlFormulario.FillColor = Color.White;
            pnlFormulario.Location = new Point(998, 128);
            pnlFormulario.Name = "pnlFormulario";
            pnlFormulario.Radius = 12;
            pnlFormulario.ShadowColor = Color.FromArgb(90, 64, 0, 0);
            pnlFormulario.ShadowDepth = 18;
            pnlFormulario.ShadowShift = 2;
            pnlFormulario.Size = new Size(530, 706);
            lblFormulario.AutoSize = true;
            lblFormulario.Font = new Font("Book Antiqua", 12F, FontStyle.Bold);
            lblFormulario.ForeColor = Color.FromArgb(64, 0, 0);
            lblFormulario.Location = new Point(30, 25);
            lblFormulario.Name = "lblFormulario";
            lblFormulario.Size = new Size(168, 28);
            lblFormulario.Text = "Datos del registro";
            lblSeleccion.AutoSize = true;
            lblSeleccion.Font = new Font("Book Antiqua", 8.5F, FontStyle.Bold);
            lblSeleccion.ForeColor = Color.Gray;
            lblSeleccion.Location = new Point(31, 60);
            lblSeleccion.Name = "lblSeleccion";
            lblSeleccion.Size = new Size(112, 20);
            lblSeleccion.Text = "Nuevo registro";
            lblNombre.AutoSize = true;
            lblNombre.Font = new Font("Book Antiqua", 9F, FontStyle.Bold);
            lblNombre.ForeColor = Color.FromArgb(64, 0, 0);
            lblNombre.Location = new Point(31, 108);
            lblNombre.Name = "lblNombre";
            lblNombre.Size = new Size(75, 21);
            lblNombre.Text = "Nombre";
            txtNombre.BorderColor = Color.FromArgb(216, 216, 216);
            txtNombre.BorderRadius = 8;
            txtNombre.DefaultText = "";
            txtNombre.FillColor = Color.FromArgb(248, 241, 242);
            txtNombre.Font = new Font("Segoe UI", 9.5F);
            txtNombre.Location = new Point(31, 137);
            txtNombre.Margin = new Padding(4, 6, 4, 6);
            txtNombre.Name = "txtNombre";
            txtNombre.PlaceholderText = "Ingrese el nombre";
            txtNombre.SelectedText = "";
            txtNombre.Size = new Size(468, 44);
            lblDescripcion.AutoSize = true;
            lblDescripcion.Font = new Font("Book Antiqua", 9F, FontStyle.Bold);
            lblDescripcion.ForeColor = Color.FromArgb(64, 0, 0);
            lblDescripcion.Location = new Point(31, 207);
            lblDescripcion.Name = "lblDescripcion";
            lblDescripcion.Size = new Size(104, 21);
            lblDescripcion.Text = "Descripción";
            txtDescripcion.BorderColor = Color.FromArgb(216, 216, 216);
            txtDescripcion.BorderRadius = 8;
            txtDescripcion.DefaultText = "";
            txtDescripcion.FillColor = Color.FromArgb(248, 241, 242);
            txtDescripcion.Font = new Font("Segoe UI", 9F);
            txtDescripcion.Location = new Point(31, 237);
            txtDescripcion.Margin = new Padding(4, 6, 4, 6);
            txtDescripcion.Multiline = true;
            txtDescripcion.Name = "txtDescripcion";
            txtDescripcion.PlaceholderText = "Descripción opcional";
            txtDescripcion.SelectedText = "";
            txtDescripcion.Size = new Size(468, 105);
            // buttons
            btnNuevo.BorderColor = Color.FromArgb(190,160,165); btnNuevo.BorderRadius = 8; btnNuevo.BorderThickness = 1; btnNuevo.FillColor = Color.White; btnNuevo.Font = new Font("Book Antiqua",8.5F,FontStyle.Bold); btnNuevo.ForeColor = Color.FromArgb(64,0,0); btnNuevo.Location = new Point(31,390); btnNuevo.Name = "btnNuevo"; btnNuevo.Size = new Size(145,44); btnNuevo.Text = "Nuevo / Limpiar"; btnNuevo.Click += btnNuevo_Click;
            btnGuardar.BorderRadius = 8; btnGuardar.FillColor = Color.FromArgb(64,0,0); btnGuardar.Font = new Font("Book Antiqua",8.5F,FontStyle.Bold); btnGuardar.ForeColor = Color.White; btnGuardar.Location = new Point(190,390); btnGuardar.Name = "btnGuardar"; btnGuardar.Size = new Size(145,44); btnGuardar.Text = "Guardar"; btnGuardar.Click += btnGuardar_Click;
            btnEditar.BorderRadius = 8; btnEditar.DisabledState.FillColor = Color.FromArgb(190,190,190); btnEditar.Enabled = false; btnEditar.FillColor = Color.FromArgb(98,48,56); btnEditar.Font = new Font("Book Antiqua",8.5F,FontStyle.Bold); btnEditar.ForeColor = Color.White; btnEditar.Location = new Point(354,390); btnEditar.Name = "btnEditar"; btnEditar.Size = new Size(145,44); btnEditar.Text = "Editar"; btnEditar.Click += btnEditar_Click;
            btnBorrar.BorderRadius = 8; btnBorrar.DisabledState.FillColor = Color.FromArgb(190,190,190); btnBorrar.Enabled = false; btnBorrar.FillColor = Color.FromArgb(128,50,58); btnBorrar.Font = new Font("Book Antiqua",8.5F,FontStyle.Bold); btnBorrar.ForeColor = Color.White; btnBorrar.Location = new Point(354,451); btnBorrar.Name = "btnBorrar"; btnBorrar.Size = new Size(145,44); btnBorrar.Text = "Borrar"; btnBorrar.Click += btnBorrar_Click;
            // form
            AutoScaleDimensions = new SizeF(10F, 25F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.FromArgb(248, 241, 242);
            ClientSize = new Size(1556, 867);
            Controls.Add(pnlFormulario);
            Controls.Add(pnlListado);
            Controls.Add(pnlEncabezado);
            FormBorderStyle = FormBorderStyle.None;
            Name = "Frm_catalogo_rapido";
            Text = "Catálogo";
            Load += Frm_catalogo_rapido_Load;
            pnlEncabezado.ResumeLayout(false); pnlEncabezado.PerformLayout(); pnlListado.ResumeLayout(false); pnlListado.PerformLayout(); ((System.ComponentModel.ISupportInitialize)dgvCatalogo).EndInit(); pnlFormulario.ResumeLayout(false); pnlFormulario.PerformLayout(); ResumeLayout(false);
        }
        #endregion

        private Guna.UI2.WinForms.Guna2Panel pnlEncabezado;
        private Guna.UI2.WinForms.Guna2Button btnVolver;
        private Label lblSubtitulo;
        private Label lblTitulo;
        private Guna.UI2.WinForms.Guna2ShadowPanel pnlListado;
        private Label lblTotal;
        private Guna.UI2.WinForms.Guna2Button btnBuscar;
        private Guna.UI2.WinForms.Guna2TextBox txtBuscar;
        private Guna.UI2.WinForms.Guna2DataGridView dgvCatalogo;
        private DataGridViewTextBoxColumn colId;
        private DataGridViewTextBoxColumn colNombre;
        private DataGridViewTextBoxColumn colDescripcion;
        private DataGridViewTextBoxColumn colEstado;
        private Guna.UI2.WinForms.Guna2ShadowPanel pnlFormulario;
        private Label lblSeleccion;
        private Guna.UI2.WinForms.Guna2Button btnNuevo;
        private Guna.UI2.WinForms.Guna2Button btnBorrar;
        private Guna.UI2.WinForms.Guna2Button btnEditar;
        private Guna.UI2.WinForms.Guna2Button btnGuardar;
        private Guna.UI2.WinForms.Guna2TextBox txtDescripcion;
        private Label lblDescripcion;
        private Guna.UI2.WinForms.Guna2TextBox txtNombre;
        private Label lblNombre;
        private Label lblFormulario;
    }
}
